services:
  postgres:
    build:
      context: .
      dockerfile: Dockerfile.postgres
    restart: always
    env_file:
        - .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_PORT=${POSTGRES_PORT}
    volumes:
      - postgres-sir:/var/lib/postgresql-sir/data
    ports:
      - '${POSTGRES_PORT}:${POSTGRES_PORT}'
    networks:
      - custom_network
  node: 
    build:
      context: .
      dockerfile: Dockerfile.node
    env_file:
      - .env
    environment:
      - PORT=${PORT}
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - postgres
    networks:
      - custom_network
    volumes:
      - ./src:/src
      - ./prisma:/prisma


networks:
  custom_network:
    name: "custom_network"
    driver: bridge
volumes:
  postgres-sir:

    